# Generated by Django 4.1.1 on 2022-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('imei_code', models.CharField(max_length=250)),
                ('notes', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'устройства',
            },
        ),
        migrations.CreateModel(
            name='Tokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('counterparty', models.TextField()),
                ('end_date', models.DateField()),
                ('tech_support', models.CharField(max_length=150)),
                ('number_of_activated_devices', models.IntegerField()),
                ('number_of_activations', models.IntegerField()),
                ('notes', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'ключ',
                'verbose_name_plural': 'ключи',
            },
        ),
    ]
