# Generated by Django 4.1.1 on 2022-09-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokes',
            name='number_of_activated_devices',
            field=models.IntegerField(default=0),
        ),
    ]
