# Generated by Django 4.1.1 on 2022-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_server', '0002_alter_tokes_number_of_activated_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokes',
            name='tech_support',
            field=models.DateField(),
        ),
    ]
