# Generated by Django 4.1.1 on 2022-10-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_server', '0003_alter_tokes_tech_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
