# Generated by Django 4.1.1 on 2022-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_server', '0004_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('counterparty', models.TextField()),
                ('end_date', models.DateField()),
                ('tech_support', models.DateField()),
                ('number_of_activated_devices', models.IntegerField(default=0)),
                ('number_of_activations', models.IntegerField()),
                ('notes', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'ключ',
                'verbose_name_plural': 'ключи',
            },
        ),
        migrations.DeleteModel(
            name='Tokes',
        ),
    ]
