# Generated by Django 4.1.1 on 2022-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_server', '0005_token_delete_tokes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='TokenErtel',
        ),
    ]
